# Generated by Django 3.2 on 2021-07-13 07:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_auto_20210713_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
